alice = set(['first_kill', 'level_10', 'treasure_hunter', 'speed_demon'])
bob = set(['first_kill', 'level_10', 'boss_slayer', 'collector'])
charlie = set(['level_10', 'treasure_hunter', 'boss_slayer', 'speed_demon', 'perfectionist'])

print("=== Achievement Tracker System ===\n")
print(f"Player alice achievements: {alice}")
print(f"Player bob achievements: {bob}")
print(f"Player charlie achievements: {charlie}\n")
print("=== Achievement Analytics ===")
all_achievements = alice.union(bob, charlie)
print(f"All unique achievements: {all_achievements}")
print(f"Total unique achievements: {len(all_achievements)}\n")
common = alice.intersection(bob, charlie)
print(f"Common to all_achievements players:{common}")
compare1 = alice.difference(bob, charlie)
compare2 = bob.difference(alice, charlie)
compare3 = charlie.difference(alice, bob)

rare = compare1.union(compare2, compare3)
print(f"Rare achievements (1 player): {rare}\n")
bob_vs_alice = alice.intersection(bob)
print(f"Alice vs Bob common: {bob_vs_alice}")
alice_unic = alice.difference(bob)
print(f"Alice unique: {alice_unic}")
bob_unic = bob.difference(alice)
print(f"Bob unique: {bob_unic}")
